kind: Deployment

replicas: 1

# leaderElection:
#   enabled: true

deschedulerPolicy:
  # nodeSelector: "key1=value1,key2=value2"
  # maxNoOfPodsToEvictPerNode: 10
  # maxNoOfPodsToEvictPerNamespace: 10
  # ignorePvcPods: true
  # evictLocalStoragePods: true
  # evictDaemonSetPods: true
  # tracing:
  #   collectorEndpoint: otel-collector.observability.svc.cluster.local:4317
  #   transportCert: ""
  #   serviceName: ""
  #   serviceNamespace: ""
  #   sampleRate: 1.0
  #   fallbackToNoOpProviderOnError: true
  profiles:
  - name: default
    pluginConfig:
    - name: DefaultEvictor
      args:
        ignorePvcPods: true
        evictLocalStoragePods: true
    - name: RemoveDuplicates
    - name: RemovePodsHavingTooManyRestarts
      args:
        podRestartThreshold: 100
        includingInitContainers: true
    - name: RemovePodsViolatingNodeAffinity
      args:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
    - name: RemovePodsViolatingNodeTaints
    - name: RemovePodsViolatingInterPodAntiAffinity
    - name: RemovePodsViolatingTopologySpreadConstraint
    - name: LowNodeUtilization
      args:
        thresholds:
          cpu: 20
          memory: 40
          # pods: 20
        targetThresholds:
          cpu: 50
          memory: 85
          # pods: 50
    plugins:
      balance:
        enabled:
        - RemoveDuplicates
        - RemovePodsViolatingTopologySpreadConstraint
        - LowNodeUtilization
      deschedule:
        enabled:
        - RemovePodsHavingTooManyRestarts
        - RemovePodsViolatingNodeTaints
        - RemovePodsViolatingNodeAffinity
        - RemovePodsViolatingInterPodAntiAffinity
