---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ../../base

helmCharts:
  - name: cert-manager
    includeCRDs: true
    repo: https://charts.jetstack.io
    version: v1.14.4
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

patches:
  - path: patch-acme-cluster-issuer.yaml
    target:
      kind: ClusterIssuer
