---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    email: joydeep.roy@omniful.com
    privateKeySecretRef:
      name: cloud-dns-letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
