# THIS PATCH IS MUST FOR SSO TO WORK 
# SEEREF - https://github.com/argoproj/argo-cd/pull/12481
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd # THIS LABEL IS MUST FOR SSO TO WORK
    app.kubernetes.io/instance: argocd
  name: argocd-notifications-secret
