apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:

  # Certificate Manager & Renewal
  - cert-manager-as.yaml

  # Secrets
  # - stakater-reloader-as.yaml

  # Descheduler
  - descheduler-as.yaml

  # Monitoring
  # - kube-prometheus-stack-as.yaml
  # - prometheus-as.yaml

# 1. By default everything is created for all environments.
# 2. Patches are applied only for Dev and removes the cluster allocation from management.
# 3. Patches are removed and applied only for overlays and not the base management cluster.
patches:
  - path: patches/management.yaml
    target:
      labelSelector: "management=true"
      kind: ApplicationSet
      name: ".*"

  - path: patches/dev.yaml
    target:
      labelSelector: "dev=true"
      kind: ApplicationSet
      name: ".*"
