apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    includeCRDs: true
    repo: https://argoproj.github.io/argo-helm
    version: v8.1.2
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml

patches:
  - path: patches/patch-argocd-cm.yaml
    target:
      name: argocd-cm
  - path: patches/patch-argocd-sso-dex-secret.yaml
    target:
      name: dex-secret
  - path: patches/patch-argocd-rbac-cm.yaml
    target:
      name: argocd-rbac-cm

  - path: patches/patch-application-controller-sa.yaml
    target:
      kind: ServiceAccount
      name: argocd-application-controller

  - path: patches/patch-argocd-server-sa.yaml
    target:
      kind: ServiceAccount
      name: argocd-server

  # - path: patches/patch-argocd-notification-cm.yaml
  #   target:
  #     name: argocd-notifications-cm
